Add link swatch and logic
shopgate-professional-services/ext-fashion-swatches pull request #16
Opened 2024-08-06 12:54 UTC by Phmank

## Description

Adds the logic to configure a link swatch that redirects to another product via the item number. The link swatch can be of type `color` or `image`. 

The link swatch depends on a property that contains the following information.

`{"linkSwatch":{"name":{"label":"","itemNumber":"","hexcode":"","additionalText":"","imgUrl":""},"name2":{"label2":"","itemNumber2":"","hexcode2":"","additionalText2":"","imgUrl2":""}}}`

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md

2024-08-19 09:28 UTC, fkloes requested changes

2024-08-19 09:28 UTC, fkloes commented on frontend/components/pdpLinkSwatch/index.jsx
> +      isLinkSwatch={!false}
why don't you just write this as `isLinkSwatch` instead of negating `false`?

2024-08-22 08:40 UTC, fkloes requested changes

2024-08-22 08:40 UTC, fkloes commented on extension-config.json
> +        "enabled": true,
is there a reason, the labels are now enabled by default?

2024-08-22 08:40 UTC, fkloes commented on frontend/components/FoldableSwatches/components/Unfolded/index.jsx
> +    justifyContent: pdpSwatchesPosition === 'variants' ? 'center' : 'start',
when `justfy-content: center` is applied, long swatch lists are cut off.

![Bildschirmfoto 2024-08-22 um 09 52 15](https://github.com/user-attachments/assets/8036a96d-e2f0-40eb-a1f7-1ee75acc8bdb)

2024-08-22 13:35 UTC, Phmank commented on extension-config.json
> +        "enabled": true,
disabled

2024-08-22 13:36 UTC, Phmank commented on frontend/components/FoldableSwatches/components/Unfolded/index.jsx
> +    justifyContent: pdpSwatchesPosition === 'variants' ? 'center' : 'start',
changed `justify-content: center` to `justify-content: safe center`

2024-08-26 07:53 UTC, fkloes approved these changes

2024-08-27 08:15 UTC, merged